import './globals.css';

import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import { cookies } from 'next/headers';

import Footer from '@/components/common/footer';
import Header from '@/components/common/header';
import { Toaster } from '@/components/ui/sonner';
import { fetchWithAuth } from '@/lib/auth';

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getUser() {
  const cookieStore = cookies();
  const accessToken = cookieStore.get('access_token')?.value;

  const headers: HeadersInit = {};
  if (accessToken) headers.cookie = `access_token=${accessToken}`;

  const res = await fetchWithAuth('/api/user', { headers });

  const data = await res.json();
  return data ?? null;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={figtree.className}>
        <div className="flex min-h-screen flex-col">
          <Header user={user} />
          <main className="flex flex-1 flex-col">{children}</main>
          <Toaster />
          <Footer />
        </div>
      </body>
    </html>
  );
}
